### ISSUE TITLE
Adding contributors profiles in README.md

### ISSUE THREAD

**Issue by sb-decoder** [DevoAbhi/WhatsSend-Frontend#15]
I want to add contributors profiles in README.md , it will automatically updated all contributors in README.md

**Comment by Petsamuel** [comment]
This issue has CREATED PREVIOUSLY

**Comment by sb-decoder** [comment]
Ok!

**Comment by DevoAbhi** [comment]
> This issue has CREATED PREVIOUSLY

No, I don't think this has been done. That issue was to mention the rules to contribute. This is to show the profile images of the contributors in the repo. Am I right @sb-decoder ?

**Comment by Sowham-3098** [comment]
Yeah !

**Comment by sb-decoder** [comment]
Yeah !

**Comment by DevoAbhi** [comment]
Yes, I am assigning you.
Mention the profiles under a separate heading like "Contributors".
