### ISSUE TITLE
Please create a link to your site in description of repo

### ISSUE THREAD

**Issue by ElvinPero** [DevoAbhi/WhatsSend-Frontend#19]

**Comment by ElvinPero** [comment]
@DevoAbhi So that people can view the curent site

**Comment by DevoAbhi** [comment]
This app is still in dev phase. I'll deploy when we have everything working.

**Comment by ElvinPero** [comment]
@DevoAbhi Having website link lets people see the progress of site without forking so that they can see the actual progress. Its good for development. Most of projects have their deployment in description. I would suggest you to add that. it is easier to access as well

**Comment by DevoAbhi** [comment]
Ok, I will deploy as soon as I can.
Thank you for the suggestion.

**Comment by DevoAbhi** [comment]
Done. 
Thank you again for your suggestion.
