### ISSUE TITLE
Dark mode is needed

### ISSUE THREAD

**Issue by ElvinPero** [DevoAbhi/WhatsSend-Frontend#2]
Dark mode is needed for almost all sites nowadays.

**Comment by ElvinPero** [comment]
@DevoAbhi I would like to work on this one

**Comment by DevoAbhi** [comment]
@ElvinPero Yeah that would be great! Go on.

**Comment by ElvinPero** [comment]
@DevoAbhi Hey! To enable nightmode I am creating a general markup of the site as well.
Could you add hacktober label on the issue .

**Comment by ElvinPero** [comment]
Currently there is no site to work on so I am creating a general markup

**Comment by DevoAbhi** [comment]
Do mean the form from the general markup?

**Comment by ElvinPero** [comment]
@DevoAbhi Yes the site layout so i can add a darkmode option

**Comment by ElvinPero** [comment]
![image](https://user-images.githubusercontent.com/101408574/194796823-e6447e93-4910-4c82-b50c-3efd5833f362.png)

**Comment by DevoAbhi** [comment]
Ok, should I assign you for the form layout issue too? You can raise this PR there.

**Comment by ElvinPero** [comment]
> Ok, should I assign you for the form layout issue too? You can raise this PR there.
@DevoAbhi I have create only sample site so i can add a dark mode there. Other person who is creating layout can merge on it. No need for other issue on same topic. thanks

**Comment by DevoAbhi** [comment]
@ElvinPero  So, after the other person has created the form, your dark mode will work on that too?

**Comment by ElvinPero** [comment]
@DevoAbhi yes

**Comment by DevoAbhi** [comment]
Ok, great.

**Comment by ElvinPero** [comment]
Hi I have created the layout on which dark mode will be added . kindly merge it with label hacktoberfest-accepted on PR

**Comment by ElvinPero** [comment]
@DevoAbhi I have added the dark mode button
