### ISSUE TITLE
Accept the time from the input and send to backend in suitable format

### ISSUE THREAD

**Issue by DevoAbhi** [DevoAbhi/WhatsSend-Frontend#20]
![Screenshot (995)](https://user-images.githubusercontent.com/54373853/195392059-84dc14b8-721f-4c96-884e-7c9b6df24e86.png)

Here time is stored as hour and min. But from input we get time in format of hour-min. 
Seperate the hour and min from this value and store it in time object in script.js file.

Ask me in comments if you have any doubts.

**Comment by Prerna-Bhargava** [comment]
Hello, I have understood the issue and would like to work on this. Please assign me this issue.

**Comment by DevoAbhi** [comment]
@Prerna-Bhargava go ahead.

**Comment by DevoAbhi** [comment]
@Prerna-Bhargava can you please look into other issues.
This issue has now been resolved by one other contributor.

**Comment by Prerna-Bhargava** [comment]
Yeah okay.
