### ISSUE TITLE
Accept the date from the input and send to backend in suitable format

### ISSUE THREAD

**Issue by DevoAbhi** [DevoAbhi/WhatsSend-Frontend#21]
![Screenshot (995)](https://user-images.githubusercontent.com/54373853/195392059-84dc14b8-721f-4c96-884e-7c9b6df24e86.png)

Here date is stored as day, month and year.
Seperate the day, month and year from this value and store it in time object in script.js file.

Ask me in comments if you have any doubts.

**Comment by kartikjoshi267** [comment]
Please assign this to me. I would like to work on it

**Comment by DevoAbhi** [comment]
Go ahead @kartikjoshi267
