### ISSUE TITLE
Design the dark mode button 

### ISSUE THREAD

**Issue by DevoAbhi** [DevoAbhi/WhatsSend-Frontend#22]

**Comment by iamdestinychild** [comment]
please assign this to me

**Comment by DevoAbhi** [comment]
Go ahead @iamdestinychild

**Comment by ElvinPero** [comment]
I already have a pretty decent template ready. You can assign this to me.
It will have the retain functionality also.
![image](https://user-images.githubusercontent.com/101408574/195409839-4185f9ea-e5aa-445d-a717-ed44878f214d.png)

**Comment by ElvinPero** [comment]
@DevoAbhi

**Comment by DevoAbhi** [comment]
@ElvinPero I have already assigned @iamdestinychild 
You can ask from @iamdestinychild if he wants to do any other issue or stick with this.

**Comment by ElvinPero** [comment]
@DevoAbhi I think he can do this  But I was saying I can do this right away. You can assign him to change night mode feature for different attributes of the site .Actually I happen to have the template ready right now @iamdestinychild

**Comment by iamdestinychild** [comment]
I'm sticking with this issue, you can pick others

**Comment by DevoAbhi** [comment]
@ElvinPero Early bird catches the bug 😅

**Comment by iamdestinychild** [comment]
@DevoAbhi I have created a pull request for this task

**Comment by iamdestinychild** [comment]
i've fixed show animation on dark mode

**Comment by DevoAbhi** [comment]
Thanks @iamdestinychild

**Comment by iamdestinychild** [comment]
please add more issus
