### ISSUE TITLE
Create different file directory 

### ISSUE THREAD

**Issue by Petsamuel** [DevoAbhi/WhatsSend-Frontend#3]
It's important to separate the files, to enable other developers/contributors access, and understand the programs.

**Comment by Petsamuel** [comment]
I would like to work on this issue

**Comment by DevoAbhi** [comment]
Can you please like to elaborate what you mean by separate the files?

**Comment by Petsamuel** [comment]
> Can you please like to elaborate what you mean by separate the files?

Having a well-structured folder for Storing CSS styles, and javascript in different file makes the project more concise and organized.

**Comment by DevoAbhi** [comment]
@Petsamuel Ok go ahead. Waiting for your PR :)

**Comment by Petsamuel** [comment]
kindly Review my PR

**Comment by DevoAbhi** [comment]
> kindly Review my PR

Please look into the PR comment
