### ISSUE TITLE
add Styles to the input fields

### ISSUE THREAD

**Issue by Petsamuel** [DevoAbhi/WhatsSend-Frontend#5]
At the moment the input fields aren't styled, styling the fields would make the program more user friendly

**Comment by DevoAbhi** [comment]
This issue has already been created #1

**Comment by Petsamuel** [comment]
> This issue has already been created #1

kindly Review my PR

**Comment by DevoAbhi** [comment]
> > This issue has already been created #1
> 
> kindly Review my PR

I have commented there
