### ISSUE TITLE
Include a contributing guildeline 

### ISSUE THREAD

**Issue by Petsamuel** [DevoAbhi/WhatsSend-Frontend#6]
The aim is to create a contribute.md file that contains the steps/guidelines for contributing to the project

**Comment by DevoAbhi** [comment]
Ok, go ahead. 
Also look into the comment of your previous PR.

**Comment by Petsamuel** [comment]
https://github.com/DevoAbhi/WhatsSend-Frontend/pull/14

**Comment by DevoAbhi** [comment]
Thanks @Petsamuel
